name: Spring CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.2
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
   #Performing Snyk scan for vulnerabilities
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven@master
      continue-on-error: true # To make sure that SARIF upload gets called
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
          command: monitor

#Dockerizing Spring Image 
          
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag spring_img:$(date +%s)

#Scanning the image using snyk
     
    - uses: actions/checkout@v3
    - name: Build a Docker image
      run: docker build -t spring_img .
    - name: Run Snyk to check Docker image for vulnerabilities
    
      continue-on-error: true
      uses: snyk/actions/docker@14818c4695ecc4045f33c9cee9e795a788711ca4
      env:
        
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: spring_img
        args: --file=Dockerfile

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif

#Scanning IAC with snyk

    - uses: actions/checkout@v3
    - name: Run Snyk to check configuration files for security issues
      continue-on-error: true
      uses: snyk/actions/iac@14818c4695ecc4045f33c9cee9e795a788711ca4
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
          file: main.tf
          args: --report
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
          sarif_file: snyk.sarif
          

#Upload image to JFROG
    - uses: actions/checkout@v3
    - name: Build image uing docker and upload to JFrog
      run:  | 
            docker build -t 172.27.59.80:8082/bansari-github-actions/spring_img:${{ github.run_number }} .
            docker login -u ${{ secrets.JFROG_USERNAME }} -p ${{ secrets.JFROG_PASSWORD }} http://172.27.59.80:8082
            docker push 172.27.59.80:8082/bansari-github-actions/spring_img:${{ github.run_number }}  
